### ISSUE TITLE
process.chdir(languagePath); Error: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by ghost** [seishun/node-steam-resources#1]
/node_modules/steam/node_modules/steam-resources/steam_language_parser/index.js:8
process.chdir(languagePath);
        ^
Error: ENOENT, no such file or directory

at Error (native)
    at Object.<anonymous> (/node_modules/steam/node_modules/steam-resources/steam_language_parser/index.js:8:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/node_modules/steam/node_modules/steam-resources/index.js:62:1)
    at Module._compile (module.js:460:26)

Linux version 2.6.32-042stab108.8 (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Wed Jul 22 17:23:23 MSK 2015

Debian GNU/Linux 7.9 (wheezy)

**Comment by seishun** [comment]
Did you run `npm install` in the module directory?

**Comment by ghost** [comment]
npm WARN cannot run in wd steam-resources@0.0.1 svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/Protobufs protobufs && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/SteamLanguage steam_language (wd=/node_modules/steam/node_modules/steam-resources)

**Comment by seishun** [comment]
Either stop running as root or add `--unsafe-perm`.

**Comment by ghost** [comment]
there's no https://github.com/SteamRE/SteamKit/trunk/Resources/SteamLanguage && https://github.com/SteamRE/SteamKit/trunk/Resources/Protobufs on the github

**Comment by seishun** [comment]
That doesn't matter. Read how GitHub works with svn.

**Comment by chiiledgamer1985** [comment]
sorry for asking but now to fix the same thing with windows ? as im getting the same error with a steambot
