### ISSUE TITLE
Issue installing steam-resources

### ISSUE THREAD

**Issue by nickbijmoer** [seishun/node-steam-resources#3]
hello i got this error:

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.<anonymous> (/root/node_modules/steam-resources/steam_language_parser/index.js:7:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/root/node_modules/steam-resources/index.js:81:1)
    at Module._compile (module.js:413:34)

**Comment by seishun** [comment]
Did you follow the installation steps in the README?

> Run npm install in the steam-resources directory to run the prepublish script (see npm/npm#3055). It pulls the Steam resources from SteamKit and requires svn.

**Comment by nickbijmoer** [comment]
Yes i did then i get this error 

root@vps260538:~/node_modules/steam-resources# npm install
npm ERR! Linux 4.2.0-18-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /root/node_modules/steam-resources/npm-debug.log

**Comment by seishun** [comment]
Can you attach your npm-debug.log file?

**Comment by nickbijmoer** [comment]
http://pastebin.com/sfs5YZVx

**Comment by seishun** [comment]
It seems to be an npm bug: https://github.com/npm/npm/issues/10686

Can't really help you.

**Comment by nickbijmoer** [comment]
Okey thanks anyway :)
