### ISSUE TITLE
Installation problems (howto?)

### ISSUE THREAD

**Issue by zmechu** [seishun/node-steam-resources#5]
Hello!

I have such errors, how to handle it :-) ?
```
root@shell:/tmp# mkdir steam
root@shell:/tmp# cd steam/
root@shell:/tmp/steam# npm install seishun/node-steam-resources
npm WARN saveError ENOENT: no such file or directory, open '/tmp/steam/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/steam/package.json'
npm WARN steam No description
npm WARN steam No repository field.
npm WARN steam No README data
npm WARN steam No license field.

+ steam-resources@1.2.0
added 37 packages from 34 contributors and audited 56 packages in 17.671s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
root@shell:/tmp/steam# npm audit fix
npm ERR! code EAUDITNOPJSON
npm ERR! audit No package.json found: Cannot audit a project without a package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-22T10_45_05_925Z-debug.log
```
```
cat /root/.npm/_logs/2019-09-22T10_45_05_925Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'audit', 'fix' ]
2 info using npm@6.10.3
3 info using node@v12.10.0
4 verbose npm-session 99133d425fe70a59
5 verbose stack Error: No package.json found: Cannot audit a project without a package.json
5 verbose stack     at /usr/lib/node_modules/npm/lib/audit.js:164:19
5 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
5 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:514:35)
5 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
5 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
5 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
5 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
5 verbose stack     at PromiseArray._resolve (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
5 verbose stack     at PromiseArray._promiseFulfilled (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:144:14)
5 verbose stack     at PromiseArray._iterate (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:114:31)
5 verbose stack     at PromiseArray.init [as _init] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:78:10)
5 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
5 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
5 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
5 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
5 verbose stack     at PromiseArray._resolve (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
6 verbose cwd /tmp/steam
7 verbose Linux 4.9.0-3-amd64
8 verbose argv "/usr/bin/node" "/usr/bin/npm" "audit" "fix"
9 verbose node v12.10.0
10 verbose npm  v6.10.3
11 error code EAUDITNOPJSON
12 error audit No package.json found: Cannot audit a project without a package.json
13 verbose exit [ 1, true ]
```

```
svn --version
svn, version 1.9.5 (r1770682)
```
```
node -v
v12.10.0
npm -v
6.10.3
```

**Comment by seishun** [comment]
As the error message says, you don't have a package.json in your project directory.

**Comment by zmechu** [comment]
Thanks :-)
Trying to install: https://github.com/Ananaskirsche/ts-csgo-rankbot:

```
root@shell:/tmp/cs2# ls -lh
total 132K
-rw-r--r-- 1 root root  431 Sep 18 17:46 README.md
drwxr-xr-x 2 root root 4.0K Sep 18 17:46 config
-rw-r--r-- 1 root root 8.6K Sep 18 17:46 database.js
-rw-r--r-- 1 root root  813 Sep 18 17:46 index.js
drwxr-xr-x 2 root root 4.0K Sep 18 17:46 locales
-rw-r--r-- 1 root root  935 Sep 18 17:46 logger.js
-rw-r--r-- 1 root root  61K Sep 18 17:46 package-lock.json
-rw-r--r-- 1 root root  519 Sep 18 17:46 package.json
-rw-r--r-- 1 root root  15K Sep 18 17:46 steam.js
-rw-r--r-- 1 root root  13K Sep 18 17:46 teamspeak.js
root@shell:/tmp/cs2# npm install seishun/node-steam-resources
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/steam/steam-resources@github:seishun/node-steam-resources#v1.2.0" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-22T10_59_06_937Z-debug.log
```
```
cat /root/.npm/_logs/2019-09-22T10_59_06_937Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'seishun/node-steam-resources'
1 verbose cli ]
2 info using npm@6.10.3
3 info using node@v12.10.0
4 verbose npm-session de3cd1b88495b28e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose prepareGitDep undefined: installing devDeps and running prepare script.
8 silly prepareGitDep 1> added 36 packages from 33 contributors and audited 55 packages in 4.202s
8 silly prepareGitDep found 1 moderate severity vulnerability
8 silly prepareGitDep   run `npm audit fix` to fix them, or `npm audit` for details
9 silly prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
9 silly prepareGitDep npm WARN lifecycle steam-resources@1.2.0~prepare: cannot run in wd steam-resources@1.2.0 svn checkout https://github.com/SteamDatabase/Protobufs/trunk protobufs && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/Protogen protogen && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/SteamLanguage steam_language (wd=/root/.npm/_cacache/tmp/git-clone-c197ca41)
10 info lifecycle steam-resources@1.2.0~prepack: steam-resources@1.2.0
11 info lifecycle steam-resources@1.2.0~postpack: steam-resources@1.2.0
12 silly pacote git manifest for undefined@github:seishun/node-steam-resources fetched in 7057ms
13 timing stage:loadCurrentTree Completed in 7209ms
14 silly install loadIdealTree
15 silly install cloneCurrentTreeToIdealTree
16 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
17 silly install loadShrinkwrap
18 timing stage:loadIdealTree:loadShrinkwrap Completed in 848ms
19 silly install loadAllDepsIntoIdealTree
20 silly resolveWithNewModule steam-resources@1.2.0 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/protobufjs 4175ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/csv-parse 4205ms (from cache)
23 silly pacote range manifest for protobufjs@^4.1 fetched in 4202ms
24 silly resolveWithNewModule protobufjs@4.1.3 checking installable status
25 silly pacote range manifest for csv-parse@^4.0.1 fetched in 4232ms
26 silly resolveWithNewModule csv-parse@4.4.6 checking installable status
27 http fetch GET 304 https://registry.npmjs.org/bytebuffer 86ms (from cache)
28 silly pacote range manifest for bytebuffer@~4 >=4.1 fetched in 99ms
29 silly resolveWithNewModule bytebuffer@4.1.0 checking installable status
30 http fetch GET 304 https://registry.npmjs.org/glob 119ms (from cache)
31 silly pacote range manifest for glob@^5.0.10 fetched in 129ms
32 silly resolveWithNewModule glob@5.0.15 checking installable status
33 http fetch GET 304 https://registry.npmjs.org/long 63ms (from cache)
34 silly pacote range manifest for long@~2 >=2.3.0 fetched in 70ms
35 silly resolveWithNewModule long@2.4.0 checking installable status
36 silly fetchPackageMetaData error for steam-resources@file:steam-resources@github:seishun/node-steam-resources#v1.2.0 Could not install from "node_modules/steam/steam-resources@github:seishun/node-steam-resources#v1.2.0" as it does not contain a package.json file.
37 timing stage:rollbackFailedOptional Completed in 2ms
38 timing stage:runTopLevelLifecycles Completed in 13028ms
39 silly saveTree ts-csgo-bot@1.0.0
[...]
40 verbose stack Error: ENOENT: no such file or directory, open '/tmp/cs2/node_modules/steam/steam-resources@github:seishun/node-steam-resources#v1.2.0/package.json'
41 verbose cwd /tmp/cs2
42 verbose Linux 4.9.0-3-amd64
43 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "seishun/node-steam-resources"
44 verbose node v12.10.0
45 verbose npm  v6.10.3
46 error code ENOLOCAL
47 error Could not install from "node_modules/steam/steam-resources@github:seishun/node-steam-resources#v1.2.0" as it does not contain a package.json file.
48 verbose exit [ 1, true ]
```

**Comment by seishun** [comment]
Something is wrong with your local setup, try clearing the cache or using another machine. Can't help you further.

**Comment by zmechu** [comment]
Just check on third machine... Any tips how to handle it?

**Comment by seishun** [comment]
No, you'll have to google it yourself. It's not a problem with the module since it clearly has a package.json file.

**Comment by Maay** [comment]
I have the same problem when trying to install dota2 package in firebase
````
Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nnpm ERR! code ENOLOCAL\nnpm ERR! Could not install from \"node_modules/steam/steam-resources@github:seishun/node-steam-resources#v1.2.0\" as it does not contain a package.json file.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2019-11-15T14_42_04_996Z-debug.log\n\nerror: `npm_install` returned code: 1", "errorType": "InternalError", "errorId": "48BA56CB"}}
```

**Comment by EloB** [comment]
I had this issue on multiple devices.

It's very easy to reproduce.
```bash
mkdir test
cd test
npm init # Press enter on everything
npm install -S steam
rm -rf node_modules
npm install
```

Outputs this error
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\steam\steam-resources@github:seishun\node-steam-resources#v1.2.0" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ollebroms\AppData\Roaming\npm-cache\_logs\2020-01-20T16_20_55_022Z-debug.log
```

```
node -v
v12.14.1

npm -v
6.13.4
```

**Comment by EloB** [comment]
The only way I can install after getting this error is to remove `package-lock.json` and `node_modules` but this isn't a solution. It's more a workaround until this is fixed. Can you open this again?

**Comment by seishun** [comment]
I don't see how this is an issue with the module. Looks like an npm bug to me.

**Comment by EloB** [comment]
Your module can't be used. All my csgo related projects can't be installed on productions servers. The only solution right is to remove `package-lock.json` and clean `node_modules` but that isn't a solution it's a workaround.

**Comment by EloB** [comment]
Tested on linux, windows, osx and multiple versions of node doesn't work anywhere.

**Comment by EloB** [comment]
If this is a `npm` bug is it reported? Have you confirmed it's a `npm` bug and please reopen this bug until it's solved.

**Comment by EloB** [comment]
I think I know what the problem is!

The svn command you do is broken.
```
svn: E170000: URL 'https://github.com/SteamRE/SteamKit/trunk/Resources/Protogen' doesn't exist
```

**Comment by alex7kom** [comment]
I have tested it on Ubuntu and macOS with the latest Node.js and npm and it installs just fine. SVN commands also work perfectly fine. If you have a problem with `npm`, it's you who should report it, because you can reproduce it. Why should it be reported by people who can't reproduce it?

**Comment by ramboi234** [comment]
same issue. please fix,,,

**Comment by ramboi234** [comment]
I use latest nodejs 12.17.0 also test on v12.16.1 didnt work
