### ISSUE TITLE
[Dota2] Error: Duplicate name in namespace Namespace : CExtraMsgBlock

### ISSUE THREAD

**Issue by worldofsites** [seishun/node-steam-resources#7]
Hi there,
I'm trying to run `node example.js` from https://github.com/Arcana/node-dota2, but errors appears:
```
~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:1530
                    throw Error("Duplicate name in namespace "+this.toString(true)+": "+child.name);
                    ^

Error: Duplicate name in namespace Namespace : CExtraMsgBlock
    at Namespace.ProtoBuf.Reflect.NamespacePrototype.addChild (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:1530:27)
    at Builder.ProtoBuf.Builder.BuilderPrototype.create (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:4470:34)
    at Builder.ProtoBuf.Builder.BuilderPrototype.import (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:4669:22)
    at Object.ProtoBuf.loadJson (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:5135:26)
    at Object.ProtoBuf.loadProto (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:5038:25)
    at Object.ProtoBuf.loadProtoFile (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:5084:52)
    at ~\node-worker\node_modules\steam-resources\index.js:41:14
    at Array.forEach (<anonymous>)
    at loadProtoFiles (~\node-worker\node_modules\steam-resources\index.js:40:9)
    at Object.<anonymous> (~\node-worker\node_modules\steam-resources\index.js:33:15)
```
I have checked code and found that commit:
https://github.com/SteamDatabase/GameTracking-Dota2/commit/ea7a913d97ad1ea85ad03d0d7fc57c9094c55c33#diff-e53f0f3df740474482f2fc18a8ae1de2
There was added `message CExtraMsgBlock` to `Protobufs/econ_gcmessages.proto`, but `message CExtraMsgBlock` already exists at `extramsgblockutil.proto`.
And removed line `import "extramsgblockutil.proto";` from `Protobufs/dota_gcmessages_server.proto`
**If I revert these changes locally, then all works.**

**Comment by seishun** [comment]
Simpler way to reproduce: `require('steam-resources')`.

**Comment by worldofsites** [comment]
@seishun Is there any way to fix it? I have tried to fix protos in GameTracking-Dota2 😁, but it's not a correct way

**Comment by seishun** [comment]
You can delete the extra message locally as a workaround.

**Comment by seishun** [comment]
https://github.com/SteamRE/SteamKit/pull/792

**Comment by seishun** [comment]
Fixed in https://github.com/SteamRE/SteamKit/commit/e243eb845bb68aa8828d827769aa3f26d61569d1.
